### PR TITLE
update to LS 1.4

### PR DESCRIPTION
**Pull request by gkz**
npm name changed, update needed

### CODE REVIEW

**Comment by DavidSouther** [comment]
It is my understanding that after this update, requesting source maps will no longer produce correct output? @chisui

**Comment by chisui** [comment]
yes, but 1.3.1 didn't have sourcemaps at all afaik.

**Comment by gkz** [comment]
1.4 is the first version with source-maps - I don't know how you want to deal with that.

**Comment by DavidSouther** [comment]
It should probably just put the .map file in the same folder; I presume that's how the livescript binary handles things?

**Comment by SEAPUNK** [comment]
+1

**Comment by FayneAldan** [comment]
+1

**Comment by DavidSouther** [comment]
Closed, in favor of #16

**Pull request closed without merging**
